# Generated by Django 3.2.7 on 2021-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fermerName', models.CharField(max_length=150)),
                ('companyName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=40)),
                ('tegs', models.ManyToManyField(to='manager.ProductTegs')),
            ],
        ),
    ]
