# Generated by Django 3.2.7 on 2021-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tegs',
            field=models.ManyToManyField(related_name='tegs_profiles', to='manager.ProductTegs'),
        ),
    ]
