# Generated by Django 3.2.7 on 2021-09-27 14:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210927_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='tegName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'пшеница'), ('2', 'семечка'), ('3', 'майонез'), ('4', 'овес'), ('5', 'жмых'), ('6', 'кусочек сыра')], max_length=11),
        ),
    ]
