# Generated by Django 3.2.7 on 2021-09-27 15:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_case_tegname'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tegName',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('пшеница', 'пшеница'), ('семечка', 'семечка'), ('майонез', 'майонез'), ('овес', 'овес'), ('жмых', 'жмых'), ('кусочек сыра', 'кусочек сыра')], max_length=46),
        ),
    ]
