# Generated by Django 3.2.7 on 2021-09-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0008_alter_case_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fermerName', models.CharField(max_length=150)),
                ('companyName', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=40)),
                ('tegName', multiselectfield.db.fields.MultiSelectField(choices=[('пшеница', 'пшеница'), ('семечка', 'семечка'), ('майонез', 'майонез'), ('овес', 'овес'), ('жмых', 'жмых'), ('кусочек сыра', 'кусочек сыра')], max_length=46)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('begin', 'начало'), ('conversation', 'переговоры'), ('selections', 'отборы'), ('end', 'завершена')], max_length=50)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
