# Generated by Django 3.2.7 on 2021-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210927_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='status',
            field=models.CharField(choices=[('begin', 'начало'), ('conversation', 'переговоры'), ('selections', 'отборы'), ('end', 'завершена')], default=1, max_length=50),
        ),
    ]
