# Generated by Django 3.2.7 on 2021-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_casemodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusModel',
        ),
        migrations.AddField(
            model_name='casemodel',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
