# Generated by Django 3.2.7 on 2021-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210928_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
