# Generated by Django 3.2.7 on 2021-09-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_casemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='status',
            field=models.CharField(choices=[('начало', 'начало'), ('переговоры', 'переговоры'), ('отборы', 'отборы'), ('завершена', 'завершена')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.casemodel')),
            ],
        ),
    ]
