# Generated by Django 3.2.7 on 2021-09-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210928_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemodel',
            name='comment',
        ),
    ]
