# Generated by Django 3.2.7 on 2021-09-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_remove_casemodel_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemodel',
            old_name='fermerName',
            new_name='farmerName',
        ),
    ]
