# Generated by Django 3.2.7 on 2021-09-29 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_fermername_casemodel_farmername'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
