# Generated by Django 3.2.7 on 2021-09-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_statusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.statusmodel'),
        ),
    ]
