# Generated by Django 3.2.7 on 2021-09-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_casemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemodel',
            name='status',
        ),
    ]
