# Generated by Django 3.2.7 on 2021-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_remove_casemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='status',
            field=models.CharField(choices=[('начало', 'начало'), ('переговоры', 'переговоры'), ('отборы', 'отборы'), ('завершена', 'завершена')], default=1, max_length=50),
        ),
    ]
