# Generated by Django 3.2.7 on 2021-09-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_casemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.statusmodel'),
        ),
    ]
