# Generated by Django 3.2.7 on 2021-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_statusmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
