# Generated by Django 3.2.7 on 2021-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_statusmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='text_comment',
            field=models.TextField(max_length=300),
        ),
    ]
