# Generated by Django 3.2.7 on 2021-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_alter_commentmodel_text_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='role',
            field=models.CharField(blank=True, choices=[('КФХ', 'КФХ'), ('АГЕНТ', 'АГЕНТ')], max_length=20, null=True),
        ),
    ]
